apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: zookeeper
    component: server
    release: zookeeper
  name: data-zookeeper-0
  namespace: zookeeper
  annotations:
    volume.beta.kubernetes.io/storage-class: ci-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ci-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: zookeeper
    component: server
    release: zookeeper
  name: data-zookeeper-1
  namespace: zookeeper
  annotations:
    volume.beta.kubernetes.io/storage-class: ci-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ci-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: zookeeper
    component: server
    release: zookeeper
  name: data-zookeeper-2
  namespace: zookeeper
  annotations:
    volume.beta.kubernetes.io/storage-class: ci-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ci-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: zookeeper
    component: server
    release: zookeeper
  name: data-zookeeper-3
  namespace: zookeeper
  annotations:
    volume.beta.kubernetes.io/storage-class: ci-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ci-storage

---

